---
kind: pipeline
name: react-ci-cd

steps:
    - name: dependencies
      image: node:9-alpine
      commands:
        - npm install
    
    - name: build
      image: node:9-alpine
      commands:
        - npm run build

    - name: tests
      image: node:9-alpine
      commands:
        - npm test

    - name: pre-release
      image: node:9-alpine
      commands:
        - tar -zcvf build.tar.gz -C build .

    - name: release
      image: plugins/github-release
      settings:
        api_key:
            from_secret: github_token
        files:
            - build.tar.gz
        when:
            event: tag

    - name: notify
      image: plugins/slack
      settings:
        webhook:
            from_secret: slack_webhook
        channel: react-ci-njandard
        username: Drone.io
        icon_url: https://avatars0.githubusercontent.com/u/2181346?s=400&v=4
